### ISSUE TITLE
No application encryption key has been specified

### ISSUE THREAD

**Issue by pacino01** [eckmarcommunity/eckmar#94]
I made some changes for the coins in the .env

Someone know how to fix it?

![image](https://github.com/eckmarcommunity/eckmar/assets/152064237/f49eefc6-507b-41be-8c78-6b4f12af0fc8)

**Comment by knulii** [comment]
try
php artisan key:generate

**Comment by pacino01** [comment]
> try php artisan key:generate

root@Database:/var/www/eckmar# php artisan key:generate
PHP Parse error:  Unclosed '{' on line 12 in /var/www/eckmar/app/Console/Kernel.php on line 45

**Comment by ffeel31** [comment]
> I made some changes for the coins in the .env
> 
> Someone know how to fix it?
> 
> ![image](https://private-user-images.githubusercontent.com/152064237/291119703-f49eefc6-507b-41be-8c78-6b4f12af0fc8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMjEyMTIsIm5iZiI6MTcwMzAyMDkxMiwicGF0aCI6Ii8xNTIwNjQyMzcvMjkxMTE5NzAzLWY0OWVlZmM2LTUwN2ItNDFiZS04Yzc4LTZiNGYxMmFmMGZjOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOVQyMTIxNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NjlmZWMyNGM0ZjI3YWVhY2IxYWY2MWZjZTU2ODkwYjFmMzU0ZmM2ZjExMGEyYjcyMzg3YWFmNTdhMjM5YjQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Sh_ORavVGIMfUdgRgFz58XMtGakZU7ptjqOK6BnZ3RY)

run this commands :
php artisan key:generate

php artisan config:cache
php artisan cache:clear
php artisan view:clear

that should fix the issue after you must have set permissions to folders

**Comment by pacino01** [comment]
All artisan command return me this error:
![image](https://github.com/eckmarcommunity/eckmar/assets/152064237/dac7e37f-ab01-4455-8751-1a4732e386fc)


![image](https://github.com/eckmarcommunity/eckmar/assets/152064237/bf9fdb12-0b55-409c-9c07-21416252fb69)
![image](https://github.com/eckmarcommunity/eckmar/assets/152064237/e2ef27d8-0d49-45b4-98f1-d02e5764e580)

I dont see a failure in the Kernel.php , someone see a failure?

**Comment by pacino01** [comment]
> > I made some changes for the coins in the .env
> > Someone know how to fix it?
> > ![image](https://private-user-images.githubusercontent.com/152064237/291119703-f49eefc6-507b-41be-8c78-6b4f12af0fc8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMjEyMTIsIm5iZiI6MTcwMzAyMDkxMiwicGF0aCI6Ii8xNTIwNjQyMzcvMjkxMTE5NzAzLWY0OWVlZmM2LTUwN2ItNDFiZS04Yzc4LTZiNGYxMmFmMGZjOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOVQyMTIxNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NjlmZWMyNGM0ZjI3YWVhY2IxYWY2MWZjZTU2ODkwYjFmMzU0ZmM2ZjExMGEyYjcyMzg3YWFmNTdhMjM5YjQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Sh_ORavVGIMfUdgRgFz58XMtGakZU7ptjqOK6BnZ3RY)
> 
> run this commands : php artisan key:generate
> 
> php artisan config:cache php artisan cache:clear php artisan view:clear
> 
> that should fix the issue after you must have set permissions to folders

If I run artisan commands my server returns me a error

**Comment by pacino01** [comment]
> try php artisan key:generate

Some other ideas?

**Comment by pacino01** [comment]
@knulii I replaced the typo fix of Kernel.pho of Knulli

root@Database:/var/www/eckmar# php artisan key:generate
PHP Fatal error:  During inheritance of ArrayAccess: Uncaught ErrorException: Re                                                                                        turn type of Illuminate\Support\Collection::offsetExists($key) should either be                                                                                         compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\Return                                                                                        TypeWillChange] attribute should be used to temporarily suppress the notice in /                                                                                        var/www/eckmar/vendor/laravel/framework/src/Illuminate/Support/Collection.php:19                                                                                        11
Stack trace:
#0 /var/www/eckmar/vendor/laravel/framework/src/Illuminate/Support/Collection.ph                                                                                        p(42): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /var/www/eckmar/vendor/composer/ClassLoader.php(576): include('...')
#2 /var/www/eckmar/vendor/composer/ClassLoader.php(427): Composer\Autoload\{clos                                                                                        ure}()
#3 /var/www/eckmar/vendor/laravel/framework/src/Illuminate/Support/helpers.php(4                                                                                        22): Composer\Autoload\ClassLoader->loadClass()
#4 /var/www/eckmar/vendor/laravel/framework/src/Illuminate/Foundation/PackageMan                                                                                        ifest.php(80): collect()
#5 /var/www/eckmar/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/                                                                                        RegisterFacades.php(26): Illuminate\Foundation\PackageManifest->aliases()
#6 /var/www/eckmar/vendor/laravel/framework/src/Illuminate/Foundation/Applicatio                                                                                        n.php(211): Illuminate\Foundation\Bootstrap\RegisterFacades->bootstrap()
#7 /var/www/eckmar/vendor/laravel/framework/src/Illuminate/Foundation/Console/Ke                                                                                        rnel.php(297): Illuminate\Foundation\Application->bootstrapWith()
#8 /var/www/eckmar/vendor/laravel/framework/src/Illuminate/Foundation/Console/Ke                                                                                        rnel.php(120): Illuminate\Foundation\Console\Kernel->bootstrap()
#9 /var/www/eckmar/artisan(35): Illuminate\Foundation\Console\Kernel->handle()
#10 {main} in /var/www/eckmar/vendor/laravel/framework/src/Illuminate/Support/Co                                                                                        llection.php on line 42
PHP Fatal error:  Uncaught ErrorException: Method ReflectionParameter::getClass(                                                                                        ) is deprecated in /var/www/eckmar/vendor/laravel/framework/src/Illuminate/Conta                                                                                        iner/Container.php:838
Stack trace:
#0 /var/www/eckmar/vendor/laravel/framework/src/Illuminate/Container/Container.p                                                                                        hp(838): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /var/www/eckmar/vendor/laravel/framework/src/Illuminate/Container/Container.p                                                                                        hp(806): Illuminate\Container\Container->resolveDependencies()
#2 /var/www/eckmar/vendor/laravel/framework/src/Illuminate/Container/Container.p                                                                                        hp(658): Illuminate\Container\Container->build()
#3 /var/www/eckmar/vendor/laravel/framework/src/Illuminate/Container/Container.p                                                                                        hp(609): Illuminate\Container\Container->resolve()
#4 /var/www/eckmar/vendor/laravel/framework/src/Illuminate/Foundation/Applicatio                                                                                        n.php(759): Illuminate\Container\Container->make()
#5 /var/www/eckmar/vendor/laravel/framework/src/Illuminate/Container/Container.p                                                                                        hp(264): Illuminate\Foundation\Application->make()
#6 /var/www/eckmar/vendor/laravel/framework/src/Illuminate/Container/Container.p                                                                                        hp(776): Illuminate\Container\Container->Illuminate\Container\{closure}()
#7 /var/www/eckmar/vendor/laravel/framework/src/Illuminate/Container/Container.p                                                                                        hp(658): Illuminate\Container\Container->build()
#8 /var/www/eckmar/vendor/laravel/framework/src/Illuminate/Container/Container.p                                                                                        hp(609): Illuminate\Container\Container->resolve()
#9 /var/www/eckmar/vendor/laravel/framework/src/Illuminate/Foundation/Applicatio                                                                                        n.php(759): Illuminate\Container\Container->make()
#10 /var/www/eckmar/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap                                                                                        /HandleExceptions.php(159): Illuminate\Foundation\Application->make()
#11 /var/www/eckmar/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap                                                                                        /HandleExceptions.php(101): Illuminate\Foundation\Bootstrap\HandleExceptions->ge                                                                                        tExceptionHandler()
#12 /var/www/eckmar/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap                                                                                        /HandleExceptions.php(87): Illuminate\Foundation\Bootstrap\HandleExceptions->ren                                                                                        derForConsole()
#13 /var/www/eckmar/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap                                                                                        /HandleExceptions.php(123): Illuminate\Foundation\Bootstrap\HandleExceptions->ha                                                                                        ndleException()
#14 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handl                                                                                        eShutdown()
#15 {main}
  thrown in /var/www/eckmar/vendor/laravel/framework/src/Illuminate/Container/Co                                                                                        ntainer.php on line 838

**Comment by knulii** [comment]
What php version do you have installed? Make sure you are using php 7.2 and larvel 5.7.
